#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <memory>
#include <QMainWindow>
//#include <scenegraph/OpenGLScene.h>

//class CS123XmlSceneParser;
class SupportCanvas3D;

class View;

namespace Ui {
    class MainWindow;
}

/**
 * @class MainWindow
 *
 * The main graphical user interface class (GUI class) for our application.
 */
class MainWindow : public QMainWindow {
    Q_OBJECT
public:
    MainWindow(QWidget *parent = 0);
    ~MainWindow();

private:
    // Auto-generated by Qt. DO NOT RENAME!
    Ui::MainWindow *ui;

    SupportCanvas3D *m_canvas3D;
    //std::unique_ptr<CS123XmlSceneParser> m_sceneParser;
    //OpenGLScene *old_glScene;
};

#endif // MAINWINDOW_H
